### ISSUE TITLE
I don't know why the dtg it does't work for me

### ISSUE THREAD

**Issue by lighthio** [KohakuBlueleaf/z-tipo-extension#16]
[TIPO-KGen]-|19:04:57|-INFO: Using transformers model KBlueLeaf/DanTagGen-delta-rev2
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /KBlueLeaf/DanTagGen-delta-rev2/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E5B1131930>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/KBlueLeaf/DanTagGen-delta-rev2/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /KBlueLeaf/DanTagGen-delta-rev2/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E5B1131930>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/KBlueLeaf/DanTagGen-delta-rev2/resolve/main/config.json
*** Error running process: F:\AI\sd-webui-aki-v4.8\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py
    Traceback (most recent call last):
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
        resolved_file = hf_hub_download(
      File "<enhanced_experience patches.hfmirror.huggingface_hub>", line 47, in hf_hub_download_wrapper_inner
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
        return fn(*args, **kwargs)
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\AI\sd-webui-aki-v4.8\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "F:\AI\sd-webui-aki-v4.8\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 339, in process
        self._process(prompt, aspect_ratio, seed + sub_seed, *args)
      File "F:\AI\sd-webui-aki-v4.8\extensions\z-a1111-sd-webui-dtg\scripts\dtg.py", line 410, in _process
        models.load_model(target, gguf, device="cpu" if gguf_use_cpu else "cuda")
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\kgen\models.py", line 104, in load_model
        text_model = LlamaForCausalLM.from_pretrained(model_name).eval().half()
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\modeling_utils.py", line 2305, in from_pretrained
        config, model_kwargs = cls.config_class.from_pretrained(
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
        config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
        config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
        resolved_config_file = cached_file(
      File "F:\AI\sd-webui-aki-v4.8\python\lib\site-packages\transformers\utils\hub.py", line 452, in cached_file
        raise EnvironmentError(
    OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like KBlueLeaf/DanTagGen-delta-rev2 is not the path to a directory containing a file named config.json.
    Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by 1lch2** [comment]
Connection timeout issue. Try use a huggingface mirror to download the model.
