### ISSUE TITLE
error

### ISSUE THREAD

**Issue by za-wa-n-go** [KohakuBlueleaf/z-tipo-extension#18]
Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension\__init__.py", line 1, in <module>
    from .nodes.tipo import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension\nodes\tipo.py", line 35, in <module>
    import kgen.models as models
ModuleNotFoundError: No module named 'kgen.models'

Cannot import X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension module for custom nodes: No module named 'kgen.models'

**Comment by moosescap** [comment]
same here

**Comment by KohakuBlueleaf** [comment]
Install `tipo-kgen` by yourself 
The node script should have installation but sometimes it break

```
pip install -U tipo-kgen
```

**Comment by KohakuBlueleaf** [comment]
I added requirements.txt
Should work in some managers or wrapper
