### ISSUE TITLE
Cannot import F:\ComfyUI\ComfyUI\custom_nodes\z-tipo-extension module for custom nodes: [WinError 2] 系统找不到指定的文 件。: 'D:\\SD2\\py310\\Lib\\site-packages\\torch\\cuda\\bin'

### ISSUE THREAD

**Issue by xueqing0622** [KohakuBlueleaf/z-tipo-extension#20]
I am use comfyui:

[TIPO-KGen]-|10:29:01|-WARNING: Llama-cpp-python cannot be imported
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\z-tipo-extension\__init__.py", line 1, in <module>
    from .nodes.tipo import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\ComfyUI\custom_nodes\z-tipo-extension\nodes\tipo.py", line 38, in <module>
    import kgen.executor.tipo as tipo
  File "F:\ComfyUI\python_embeded\Lib\site-packages\kgen\executor\tipo.py", line 5, in <module>
    from ..generate import generate
  File "F:\ComfyUI\python_embeded\Lib\site-packages\kgen\generate.py", line 11, in <module>
    from llama_cpp import Llama
  File "F:\ComfyUI\python_embeded\Lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "F:\ComfyUI\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\llama_cpp\llama_cpp.py", line 59, in _load_shared_library
    os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\SD2\\py310\\Lib\\site-packages\\torch\\cuda\\bin'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\z-tipo-extension module for custom nodes: [WinError 2] 系统找不到指定的文 件。: 'D:\\SD2\\py310\\Lib\\site-packages\\torch\\cuda\\bin'

**Comment by xueqing0622** [comment]
我的comfyui和SD都知道\py310\Lib\site-packages\torch\cuda\这一层， 没有bin这个文件，或者这个文件夹

**Comment by xueqing0622** [comment]
自己去cuda\这一层建了两个目录搞定了bin和lib
