### ISSUE TITLE
 sqlite3.InterfaceError: Error binding parameter 1 when attempting to download 500M TIPO model

### ISSUE THREAD

**Issue by Khusanbek1** [KohakuBlueleaf/z-tipo-extension#25]
This is the error I get using V1.10.1 of Auto1111:

[TIPO-KGen]-|13:22:26|-INFO: Downloading gguf model from KBlueLeaf/TIPO-500M█████████████████████████████| 27/27 [00:16<00:00,  1.78it/s]
*** Error running process: J:\ai\stable-diffusion-webui\extensions\z-tipo-extension\scripts\tipo.py
    Traceback (most recent call last):
      File "J:\ai\stable-diffusion-webui\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "J:\ai\stable-diffusion-webui\extensions\z-tipo-extension\scripts\tipo.py", line 436, in process
        self._process(prompt, nl_prompt, aspect_ratio, seed + sub_seed, *args)
      File "J:\ai\stable-diffusion-webui\extensions\z-tipo-extension\scripts\tipo.py", line 505, in _process
        models.download_gguf(model_name, gguf_name)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\kgen\models.py", line 58, in download_gguf
        result = hf_hub_download(
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1461, in hf_hub_download
        http_get(
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 468, in http_get
        r = _request_wrapper(
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 425, in _request_wrapper
        response = get_session().request(method=method, url=url, **params)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\session.py", line 183, in request
        return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 587, in request
        resp = self.send(prep, **send_kwargs)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\session.py", line 230, in send
        response = self._send_and_cache(request, actions, cached_response, **kwargs)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\session.py", line 258, in _send_and_cache
        self.cache.save_response(response, actions.cache_key, actions.expires)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\backends\base.py", line 100, in save_response
        self.responses[cache_key] = cached_response
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\backends\sqlite.py", line 327, in __setitem__
        self._write(key, value)
      File "J:\ai\stable-diffusion-webui\venv\lib\site-packages\requests_cache\backends\sqlite.py", line 349, in _write
        con.execute(
    sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.

The extension downloads the KBlueLeaf/TIPO-200M | TIPO-200M-40Btok-F16.gguf model fine. Even if I download TIPO-500M_epoch5-F16.gguf from the repo and place it in the z-tipo-extension models folder I still get the same error. 
Downloading models for DanTagGen still works as normal just this one model is not cooperating.  
I have tried updating kgen and requests cache libraries. Deleting the requests cache. Extension is updated. Nothing is working. 

Any help would be appreciated. 

Thanks.

**Comment by KohakuBlueleaf** [comment]
You may want to try to update the "huggingface_hub" package in the environment as well
