### ISSUE TITLE
ValueError: Seed must be between 0 and 2**32 - 1

### ISSUE THREAD

**Issue by pilaoda** [KohakuBlueleaf/z-tipo-extension#27]
```
[TIPO-KGen]-|20:13:41|-INFO: Processing propmt: 1girl,solo,trxx,crossbow,holding crossbo...
[TIPO-KGen]-|20:13:41|-INFO: Processing with seed: 4324379876
*** Error running process: D:\ai\sd-webui-aki\sd-webui-aki-v4.8\extensions\z-tipo-extension\scripts\tipo.py
    Traceback (most recent call last):
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\modules\scripts.py", line 844, in process
        script.process(p, *script_args)
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\extensions\z-tipo-extension\scripts\tipo.py", line 436, in process
        self._process(prompt, nl_prompt, aspect_ratio, seed + sub_seed, *args)
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\extensions\z-tipo-extension\scripts\tipo.py", line 565, in _process
        tag_map, _ = tipo_runner(
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\kgen\executor\tipo.py", line 398, in tipo_runner
        for parsed, timing in tipo_runner_generator(
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\kgen\executor\tipo.py", line 372, in tipo_runner_generator
        for result, parsed in generate_with_retry(
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\kgen\executor\tipo.py", line 317, in generate_with_retry
        result, input_token_count, token_generated = generate(
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\kgen\generate.py", line 49, in generate
        set_seed(kwargs["seed"])
      File "D:\ai\sd-webui-aki\sd-webui-aki-v4.8\python\lib\site-packages\transformers\trainer_utils.py", line 102, in set_seed
        np.random.seed(seed)
      File "numpy\\random\\mtrand.pyx", line 4805, in numpy.random.mtrand.seed
      File "numpy\\random\\mtrand.pyx", line 250, in numpy.random.mtrand.RandomState.seed
      File "_mt19937.pyx", line 168, in numpy.random._mt19937.MT19937._legacy_seeding
      File "_mt19937.pyx", line 182, in numpy.random._mt19937.MT19937._legacy_seeding
    ValueError: Seed must be between 0 and 2**32 - 1
```

sd-webui use seed `3804849406`, but two places add it without mod may cause the overflow:
https://github.com/KohakuBlueleaf/z-tipo-extension/blob/a88c6fd103722b7b2fd41ba4a673d3b634207f29/scripts/tipo.py#L436
https://github.com/KohakuBlueleaf/KGen/blob/55c9ce91fbdfbc889447c4be8bce3c9330878f74/src/kgen/executor/tipo.py#L314

I guess mod it in the `KGen` last step before passing into `set_seed` would solve this problem

**Comment by KohakuBlueleaf** [comment]
fixed in `tipo-kgen>=0.1.3`
you can update by yourself
