### ISSUE TITLE
ComfyUI import failed

### ISSUE THREAD

**Issue by SirVeggie** [KohakuBlueleaf/z-tipo-extension#29]
I can't install this extension for ComfyUI, since it fails to load the extension due to the following error:
```
Traceback (most recent call last):
  File "S:\Library\Software\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\Library\Software\comfyui\ComfyUI\custom_nodes\z-tipo-extension\__init__.py", line 1, in <module>
    from .nodes.tipo import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "S:\Library\Software\comfyui\ComfyUI\custom_nodes\z-tipo-extension\nodes\tipo.py", line 38, in <module>
    import kgen.models as models
ModuleNotFoundError: No module named 'kgen'

Cannot import S:\Library\Software\comfyui\ComfyUI\custom_nodes\z-tipo-extension module for custom nodes: No module named 'kgen'
```

ComfyUI is up to date and I also tried with a clean install, but no dice.

**Comment by KohakuBlueleaf** [comment]
the installation code failed on your env
install `tipo-kgen` library through pip by yourself

**Comment by SirVeggie** [comment]
I'm not a python guru, but it seems to me that the extension is installing the requirements in the wrong location?
```
Attempting to install LLaMA-CPP-Python
Looking in indexes: https://pypi.org/simple, https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu121
Requirement already satisfied: llama-cpp-python in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (0.2.26+cu121)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from llama-cpp-python) (4.12.2)
Requirement already satisfied: diskcache>=5.6.1 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: numpy>=1.20.0 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from llama-cpp-python) (2.1.2)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: tipo-kgen>=0.1.2 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (0.1.3)
Requirement already satisfied: huggingface-hub in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from tipo-kgen>=0.1.2) (0.25.2)
Requirement already satisfied: transformers in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from tipo-kgen>=0.1.2) (4.45.2)
Requirement already satisfied: torch in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from tipo-kgen>=0.1.2) (2.4.1)
Requirement already satisfied: requests in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (6.0.2)
Requirement already satisfied: filelock in c:\users\veggie\appdata\roaming\python\python310\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (3.10.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (4.12.2)
Requirement already satisfied: packaging>=20.9 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (23.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (2024.9.0)
Requirement already satisfied: sympy in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (1.13.3)
Requirement already satisfied: jinja2 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (3.1.4)
Requirement already satisfied: networkx in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (3.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (0.20.1)
Requirement already satisfied: numpy>=1.17 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (2.1.2)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (0.4.5)
Requirement already satisfied: regex!=2019.12.17 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (2024.9.11)
Requirement already satisfied: colorama in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->tipo-kgen>=0.1.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch->tipo-kgen>=0.1.2) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (2023.7.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (2.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (3.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\veggie\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch->tipo-kgen>=0.1.2) (1.3.0)
```

**Comment by KohakuBlueleaf** [comment]
Yes but it is somehow expected 
It is very easy to prevent any python code to install things in a specific env

So it is impossible for me to ensure all the ppl can get automatic installation 

Please install required lib by yourself

**Comment by SirVeggie** [comment]
I fixed the issue by using the following code instead of os.system("pip install ...")
![image](https://github.com/user-attachments/assets/c0e934bd-c09c-4172-85f2-ce89ed3253b1)
This should be the intended approach based on other extensions that I looked into.

**Comment by KohakuBlueleaf** [comment]
> I fixed the issue by using the following code instead of `os.system("pip install ...")` ![image](https://private-user-images.githubusercontent.com/32365239/375714371-c0e934bd-c09c-4172-85f2-ce89ed3253b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDE0MjIsIm5iZiI6MTcyODY0MTEyMiwicGF0aCI6Ii8zMjM2NTIzOS8zNzU3MTQzNzEtYzBlOTM0YmQtYzA5Yy00MTcyLTg1ZjItY2U4OWVkMzI1M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEwMDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlOTQxN2NiZmI0Yzk4ZWYxMmFkM2ZhODVhMTk0MDAxZWQxMTIwNjI1MjQwY2EyNGFkNDVjMGE5ZGI3YjFmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ZE3NCXddIkP-j5JZF3xEwCCqSO91R8mkaF8zyWcdrM) This should be the intended approach based on other extensions that I looked into.

No
This still can't ensure all the situation 
But this is "better"

**Comment by SirVeggie** [comment]
Should I make a pull request for it?

**Comment by KohakuBlueleaf** [comment]
> Should I make a pull request for it?

It's fine
If you want to do that, try to wrap the installation things into one function for possible future use
