### ISSUE TITLE
Errors when installing extension 

### ISSUE THREAD

**Issue by Mirsem13** [KohakuBlueleaf/z-tipo-extension#31]
When trying to install an extension in SD-WebUI, multiple errors appear.
SD-WebUI latest version.

```
*** Error running install.py for extension D:\stable-diffusion-webui\webui\extensions\z-tipo-extension.
*** Command: "D:\stable-diffusion-webui\system\python\python.exe" "D:\stable-diffusion-webui\webui\extensions\z-tipo-extension\install.py"
*** Error code: 1
*** stdout: Attempting to install tipo_kgen
*** Installing tipo-kgen for DanTagGen
***
*** stderr: D:\stable-diffusion-webui\webui\extensions\z-tipo-extension\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "D:\stable-diffusion-webui\webui\extensions\z-tipo-extension\install.py", line 51, in <module>
***     install_tipo_kgen()
***   File "D:\stable-diffusion-webui\webui\extensions\z-tipo-extension\install.py", line 44, in install_tipo_kgen
***     launch.run_pip(
***   File "D:\stable-diffusion-webui\webui\modules\launch_utils.py", line 144, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\stable-diffusion-webui\webui\modules\launch_utils.py", line 116, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install tipo-kgen for DanTagGen.
*** Command: "D:\stable-diffusion-webui\system\python\python.exe" -m pip install -U "tipo-kgen>=0.1.2" --prefer-binary
*** Error code: 2
*** stdout: Collecting tipo-kgen>=0.1.2
***   Using cached tipo_kgen-0.1.3.tar.gz (5.0 MB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***
*** stderr: ERROR: Exception:
*** Traceback (most recent call last):
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
***     status = _inner_run()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
***     return self.run(options, args)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
***     return func(self, options, args)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
***     requirement_set = resolver.resolve(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
***     result = self._result = resolver.resolve(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
***     state = resolution.resolve(requirements, max_rounds=max_rounds)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
***     self._add_to_criteria(self.state.criteria, r, parent=None)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
***     if not criterion.candidates:
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
***     return bool(self._sequence)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
***     return any(self)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
***     return (c for c in iterator if id(c) not in self._incompatible_ids)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
***     candidate = func()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link
***     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
***     self._link_candidate_cache[link] = LinkCandidate(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
***     super().__init__(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
***     self.dist = self._prepare()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
***     dist = self._prepare_distribution()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
***     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
***     return self._prepare_linked_requirement(req, parallel_builds)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
***     dist = _get_prepared_distribution(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
***     abstract_dist.prepare_distribution_metadata(
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
***     self._install_build_reqs(finder)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
***     build_reqs = self._get_build_requires_wheel()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
***     return backend.get_requires_for_build_wheel()
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 706, in get_requires_for_build_wheel
***     return super().get_requires_for_build_wheel(config_settings=cs)
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
***     return self._call_hook('get_requires_for_build_wheel', {
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
***     raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
***   File "D:\stable-diffusion-webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
***     obj = import_module(mod_path)
***   File "importlib\__init__.py", line 126, in import_module
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\Users\mirse\AppData\Local\Temp\pip-build-env-55fhmxxp\overlay\Lib\site-packages\setuptools\__init__.py", line 27, in <module>
***     from .dist import Distribution
***   File "C:\Users\mirse\AppData\Local\Temp\pip-build-env-55fhmxxp\overlay\Lib\site-packages\setuptools\dist.py", line 27, in <module>
***     from . import (
***   File "C:\Users\mirse\AppData\Local\Temp\pip-build-env-55fhmxxp\overlay\Lib\site-packages\setuptools\_entry_points.py", line 6, in <module>
***     from jaraco.text import yield_lines
***   File "C:\Users\mirse\AppData\Local\Temp\pip-build-env-55fhmxxp\overlay\Lib\site-packages\setuptools\_vendor\jaraco\text\__init__.py", line 12, in <module>
***     from jaraco.context import ExceptionTrap
***   File "C:\Users\mirse\AppData\Local\Temp\pip-build-env-55fhmxxp\overlay\Lib\site-packages\setuptools\_vendor\jaraco\context.py", line 11, in <module>
***     import urllib.request
***   File "urllib\request.py", line 88, in <module>
***   File "http\client.py", line 71, in <module>
***   File "email\parser.py", line 12, in <module>
***   File "email\feedparser.py", line 27, in <module>
***   File "email\_policybase.py", line 9, in <module>
***   File "email\utils.py", line 29, in <module>
***   File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
***
```

**Comment by KohakuBlueleaf** [comment]
Your python is installed wrong.
try to use different python env like install python through conda or official site.
