### ISSUE TITLE
ComfyUI TIPO custom node fail to import

### ISSUE THREAD

**Issue by LeF0URBE** [KohakuBlueleaf/z-tipo-extension#32]
Here is what the log says at the start of ComfyUI :

Attempting to install LLaMA-CPP-Python
Looking in indexes: https://pypi.org/simple, https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122
Requirement already satisfied: llama-cpp-python in c:\python310\lib\site-packages (0.2.26+cu122)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\python310\lib\site-packages (from llama-cpp-python) (4.9.0)
Requirement already satisfied: numpy>=1.20.0 in c:\python310\lib\site-packages (from llama-cpp-python) (1.23.5)
Requirement already satisfied: diskcache>=5.6.1 in c:\python310\lib\site-packages (from llama-cpp-python) (5.6.3)
WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Requirement already satisfied: tipo-kgen>=0.1.2 in c:\python310\lib\site-packages (0.1.3)
Requirement already satisfied: transformers in c:\python310\lib\site-packages (from tipo-kgen>=0.1.2) (4.44.2)
Requirement already satisfied: huggingface-hub in c:\python310\lib\site-packages (from tipo-kgen>=0.1.2) (0.24.5)
Requirement already satisfied: torch in c:\python310\lib\site-packages (from tipo-kgen>=0.1.2) (2.2.0+cu118)
Requirement already satisfied: filelock in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (2023.10.0)
Requirement already satisfied: packaging>=20.9 in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (23.2)
Requirement already satisfied: pyyaml>=5.1 in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (6.0.1)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (4.66.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\python310\lib\site-packages (from huggingface-hub->tipo-kgen>=0.1.2) (4.9.0)
Requirement already satisfied: sympy in c:\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (1.12)
Requirement already satisfied: networkx in c:\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (3.2.1)
Requirement already satisfied: jinja2 in c:\python310\lib\site-packages (from torch->tipo-kgen>=0.1.2) (3.1.2)
Requirement already satisfied: numpy>=1.17 in c:\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (1.23.5)
Requirement already satisfied: regex!=2019.12.17 in c:\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (2023.10.3)
Requirement already satisfied: safetensors>=0.4.1 in c:\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\python310\lib\site-packages (from transformers->tipo-kgen>=0.1.2) (0.19.1)
Requirement already satisfied: colorama in c:\python310\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->tipo-kgen>=0.1.2) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from jinja2->torch->tipo-kgen>=0.1.2) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests->huggingface-hub->tipo-kgen>=0.1.2) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in c:\python310\lib\site-packages (from sympy->torch->tipo-kgen>=0.1.2) (1.3.0)
WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Traceback (most recent call last):
  File "B:\AI\img\ComfyUI_4\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "B:\AI\img\ComfyUI_4\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension\__init__.py", line 1, in <module>
    from .nodes.tipo import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "B:\AI\img\ComfyUI_4\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension\nodes\tipo.py", line 40, in <module>
    import kgen.models as models
ModuleNotFoundError: No module named 'kgen'

Cannot import B:\AI\img\ComfyUI_4\ComfyUI_windows_portable\ComfyUI\custom_nodes\z-tipo-extension module for custom nodes: No module named 'kgen'

**Comment by KohakuBlueleaf** [comment]
install `tipo-kgen` library by yourself (use pip)
it looks like your environement have some issues in auto installing

**Comment by ChiNoel-osu** [comment]
It looks like it's installing dependencies into the main env (the default one when you simply launch `python`) instead of the CompyUI's env (which in its portable version, it's embedded).
