### ISSUE TITLE
kgen.executor.tipo.generate_with_retry() got multiple values for keyword argument 'seed'

### ISSUE THREAD

**Issue by dreamflange** [KohakuBlueleaf/z-tipo-extension#53]
Thank you for developing such a great tool.
I'm using z-tipo-extension with comfyui, but tipo-kgen 0.1.7 seems to cause an error.
I downgraded tipo-kgen to 0.1.6 and it works fine.

I'll post a dump below.

# ComfyUI Error Report
## Error Details
- **Node ID:** 1
- **Node Type:** TIPO
- **Exception Type:** TypeError
- **Exception Message:** kgen.executor.tipo.generate_with_retry() got multiple values for keyword argument 'seed'
## Stack Trace
```
  File "/var/opt/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/var/opt/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/var/opt/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/var/opt/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/var/opt/ComfyUI/custom_nodes/z-tipo-extension/nodes/tipo.py", line 349, in execute
    tag_map, _ = tipo_runner(

  File "/var/opt/ComfyUI/venv/lib/python3.10/site-packages/kgen/executor/tipo.py", line 462, in tipo_runner
    for parsed, timing in tipo_runner_generator(

  File "/var/opt/ComfyUI/venv/lib/python3.10/site-packages/kgen/executor/tipo.py", line 433, in tipo_runner_generator
    for result, parsed in generate_with_retry(

```
## System Information
- **ComfyUI Version:** v0.3.7-33-g6d1a3f7
- **Arguments:** /notebooks/ComfyUI/main.py --listen --port 6006 --preview-method auto
- **OS:** posix
- **Python Version:** 3.10.15 (main, Nov 11 2024, 06:50:58) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 51041271808
  - **VRAM Free:** 50543103872
  - **Torch VRAM Total:** 201326592
  - **Torch VRAM Free:** 561024

## Logs
```
2024-12-15T21:18:55.647114 - [START] Security scan2024-12-15T21:18:55.647130 - 
2024-12-15T21:18:56.306626 - [DONE] Security scan2024-12-15T21:18:56.306648 - 
2024-12-15T21:18:56.349123 - ## ComfyUI-Manager: installing dependencies done.2024-12-15T21:18:56.349177 - 
2024-12-15T21:18:56.349197 - ** ComfyUI startup time:2024-12-15T21:18:56.349213 -  2024-12-15T21:18:56.349231 - 2024-12-15 21:18:56.3491872024-12-15T21:18:56.349247 - 
2024-12-15T21:18:56.349264 - ** Platform:2024-12-15T21:18:56.349278 -  2024-12-15T21:18:56.349292 - Linux2024-12-15T21:18:56.349306 - 
2024-12-15T21:18:56.349321 - ** Python version:2024-12-15T21:18:56.349334 -  2024-12-15T21:18:56.349348 - 3.10.15 (main, Nov 11 2024, 06:50:58) [GCC 11.4.0]2024-12-15T21:18:56.349363 - 
2024-12-15T21:18:56.349377 - ** Python executable:2024-12-15T21:18:56.349391 -  2024-12-15T21:18:56.349405 - /var/opt/ComfyUI/venv/bin/python2024-12-15T21:18:56.349419 - 
2024-12-15T21:18:56.349433 - ** ComfyUI Path:2024-12-15T21:18:56.349447 -  2024-12-15T21:18:56.349460 - /notebooks/ComfyUI2024-12-15T21:18:56.349474 - 
2024-12-15T21:18:56.349502 - ** Log path:2024-12-15T21:18:56.349517 -  2024-12-15T21:18:56.349531 - /var/opt/ComfyUI/comfyui.log2024-12-15T21:18:56.349545 - 
2024-12-15T21:18:57.239461 - 
Prestartup times for custom nodes:2024-12-15T21:18:57.239566 - 
2024-12-15T21:18:57.239626 -    1.6 seconds:2024-12-15T21:18:57.239626 -  2024-12-15T21:18:57.239640 - /var/opt/ComfyUI/custom_nodes/ComfyUI-Manager2024-12-15T21:18:57.239665 - 
2024-12-15T21:18:57.239725 - 
2024-12-15T21:18:58.500841 - Total VRAM 48677 MB, total RAM 45140 MB
2024-12-15T21:18:58.500992 - pytorch version: 2.5.1+cu124
2024-12-15T21:18:58.501499 - Set vram state to: NORMAL_VRAM
2024-12-15T21:18:58.501643 - Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
2024-12-15T21:18:59.515944 - Using pytorch cross attention
2024-12-15T21:19:00.576389 - [Prompt Server] web root: /var/opt/ComfyUI/web
2024-12-15T21:19:00.816974 - ### Loading: ComfyUI-Manager (V2.55.5)2024-12-15T21:19:00.817024 - 
2024-12-15T21:19:00.853126 - ### ComfyUI Version: v0.3.7-33-g6d1a3f7 | Released on '2024-12-15'2024-12-15T21:19:00.853171 - 
2024-12-15T21:19:00.858160 - timm is not installed. Skipping load wd-tagger.2024-12-15T21:19:00.858361 - 
2024-12-15T21:19:00.858915 - timm is not installed. Skipping load wd-tagger.2024-12-15T21:19:00.858955 - 
2024-12-15T21:19:00.884994 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-15T21:19:00.885429 - 
2024-12-15T21:19:00.928774 - /var/opt/ComfyUI/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2024-12-15T21:19:00.947122 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-15T21:19:00.947238 - 
2024-12-15T21:19:00.981701 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-15T21:19:00.981770 - 
2024-12-15T21:19:00.994270 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-15T21:19:00.994385 - 
2024-12-15T21:19:01.017372 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-15T21:19:01.017436 - 
2024-12-15T21:19:01.484359 - FaceDetailer: Model directory already exists2024-12-15T21:19:01.484436 - 
2024-12-15T21:19:01.484517 - FaceDetailer: Model already exists2024-12-15T21:19:01.484555 - 
2024-12-15T21:19:03.542421 - Attempting to install LLaMA-CPP-Python2024-12-15T21:19:03.542475 - 
2024-12-15T21:19:04.232639 - [TIPO-KGen]-|21:19:04|-[0;33mWARNING[0m: Llama-cpp-python cannot be imported
2024-12-15T21:19:04.375655 - [TIPO-KGen]-|21:19:04|-[0;32mINFO[0m: Using model dir: /var/opt/ComfyUI/models/kgen
2024-12-15T21:19:04.376438 - ### Loading: Save as Webp2024-12-15T21:19:04.376476 - 
2024-12-15T21:19:04.376510 - Copying JS files for Workflow loading2024-12-15T21:19:04.376530 - 
2024-12-15T21:19:04.414265 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /var/opt/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2024-12-15T21:19:04.414361 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-15T21:19:04.414424 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-15T21:19:04.429976 - /var/opt/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2024-12-15T21:19:04.470435 - [34mhus' utility nodes: [92mloaded[0m2024-12-15T21:19:04.470487 - 
2024-12-15T21:19:04.471375 - ### Loading: ComfyUI-Impact-Pack (V8.0.1)2024-12-15T21:19:04.471410 - 
2024-12-15T21:19:04.492700 - [Impact Pack] Wildcards loading done.2024-12-15T21:19:04.492804 - 
2024-12-15T21:19:04.493562 - 
Import times for custom nodes:
2024-12-15T21:19:04.493710 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/websocket_image_save.py
2024-12-15T21:19:04.493761 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ControlNet-LLLite-ComfyUI
2024-12-15T21:19:04.493821 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI_hus_utils
2024-12-15T21:19:04.493865 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI_yanc
2024-12-15T21:19:04.493944 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/comfyui_ab_samplercustom
2024-12-15T21:19:04.494004 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/cg-use-everywhere
2024-12-15T21:19:04.494046 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/comfyui-inpaint-nodes
2024-12-15T21:19:04.494269 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-12-15T21:19:04.494342 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI-Image-Saver
2024-12-15T21:19:04.494385 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
2024-12-15T21:19:04.494427 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI-Saveaswebp
2024-12-15T21:19:04.494475 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-12-15T21:19:04.494517 -    0.0 seconds: /var/opt/ComfyUI/custom_nodes/ComfyUI-Manager
2024-12-15T21:19:04.494559 -    0.1 seconds: /var/opt/ComfyUI/custom_nodes/comfyui-tooling-nodes
2024-12-15T21:19:04.494599 -    0.1 seconds: /var/opt/ComfyUI/custom_nodes/cgem156-ComfyUI
2024-12-15T21:19:04.494639 -    0.1 seconds: /var/opt/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-12-15T21:19:04.494678 -    0.8 seconds: /var/opt/ComfyUI/custom_nodes/z-tipo-extension
2024-12-15T21:19:04.494719 -    2.6 seconds: /var/opt/ComfyUI/custom_nodes/DZ-FaceDetailer
2024-12-15T21:19:04.494757 - 
2024-12-15T21:19:04.506366 - Starting server

2024-12-15T21:19:04.506830 - https://tensorboard-n9c0sgbw6z.clg07azjl.paperspacegradient.com2024-12-15T21:19:04.506865 - 
2024-12-15T21:19:04.506989 - https://tensorboard-n9c0sgbw6z.clg07azjl.paperspacegradient.com2024-12-15T21:19:04.507013 - 
2024-12-15T21:19:11.022783 - FETCH DATA from: /var/opt/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-12-15T21:19:11.022863 - 2024-12-15T21:19:11.026241 -  [DONE]2024-12-15T21:19:11.026320 - 
2024-12-15T21:19:11.316284 - Error. No styles.csv found. Put your styles.csv in /var/opt/ComfyUI/custom_nodes/ComfyUI_hus_utils/styles.csv. Then press "Refresh".
            2024-12-15T21:19:11.316371 - 
2024-12-15T21:19:11.316399 - Error. No styles.csv found. Put your styles.csv in /var/opt/ComfyUI/custom_nodes/ComfyUI_hus_utils/styles.csv. Then press "Refresh".
            2024-12-15T21:19:11.316463 - 
2024-12-15T21:19:13.103400 - got prompt
2024-12-15T21:19:13.106038 - [TIPO-KGen]-|21:19:13|-[0;32mINFO[0m: Using transformers model KBlueLeaf/TIPO-100M
2024-12-15T21:19:13.450919 - [TIPO-KGen]-|21:19:13|-[0;32mINFO[0m: Model KBlueLeaf/TIPO-100M loaded
2024-12-15T21:19:13.451340 - !!! Exception during processing !!! kgen.executor.tipo.generate_with_retry() got multiple values for keyword argument 'seed'
2024-12-15T21:19:13.451895 - Traceback (most recent call last):
  File "/var/opt/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/var/opt/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/var/opt/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/var/opt/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/var/opt/ComfyUI/custom_nodes/z-tipo-extension/nodes/tipo.py", line 349, in execute
    tag_map, _ = tipo_runner(
  File "/var/opt/ComfyUI/venv/lib/python3.10/site-packages/kgen/executor/tipo.py", line 462, in tipo_runner
    for parsed, timing in tipo_runner_generator(
  File "/var/opt/ComfyUI/venv/lib/python3.10/site-packages/kgen/executor/tipo.py", line 433, in tipo_runner_generator
    for result, parsed in generate_with_retry(
TypeError: kgen.executor.tipo.generate_with_retry() got multiple values for keyword argument 'seed'

2024-12-15T21:19:13.452245 - Prompt executed in 0.35 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":2,"last_link_id":1,"nodes":[{"id":2,"type":"ShowText|pysssss","pos":[760,1160],"size":[560,470],"flags":{},"order":1,"mode":0,"inputs":[{"name":"text","type":"STRING","link":1,"widget":{"name":"text"}}],"outputs":[{"name":"STRING","type":"STRING","links":null,"shape":6}],"properties":{"Node name for S&R":"ShowText|pysssss"},"widgets_values":[""]},{"id":1,"type":"TIPO","pos":[110,1190],"size":[450,920],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"prompt","type":"STRING","links":[1],"slot_index":0},{"name":"user_prompt","type":"STRING","links":null},{"name":"unformatted_prompt","type":"STRING","links":null},{"name":"unformatted_user_prompt","type":"STRING","links":null}],"properties":{"Node name for S&R":"TIPO"},"widgets_values":["1girl","","","KBlueLeaf/TIPO-100M","<|general|>,\n",1024,1024,0.5,0.95,0.05,80,"long","long",152,"randomize","cuda"]}],"links":[[1,1,0,2,0,"STRING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917359,"offset":[105.12082024477456,-1041.7913224656243]},"ue_links":[]},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by KohakuBlueleaf** [comment]
Should be fixed in 0.1.8
